global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: document-generator-api
    metrics_path: /metrics
    static_configs:
      - targets: ['api:3000']
        labels:
          role: api
  - job_name: document-generator-worker
    metrics_path: /metrics
    static_configs:
      - targets: ['worker:9464']
        labels:
          role: worker
